INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) VALUES ('abt', 'Audi Sport Team Abt Sportsline', 3);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) VALUES ('pho', 'Audi Sport Team Phoenix', 3);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) VALUES ('ros', 'Audi Sport Team Rosberg', 3);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) VALUES ('rbm', 'BMW Team RBM', 2);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) VALUES ('rmg', 'BMW Team RMG', 2);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) VALUES ('mte', 'BMW Team MTEK', 2);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) VALUES ('sch', 'BMW Team Schnitzer', 2);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) VALUES ('art', 'Mercedes-AMG DTM Team ART', 1);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) VALUES ('hwa', 'Mercedes-AMG DTM Team HWA', 1);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) VALUES ('mue', 'Mercedes-AMG DTM Team Mücke', 1);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'JELMA PHILIPPINES INC', 1);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Changshu Starsea Pharmaceutical Co., Ltd.', 2);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'ALK-Abello, Inc.', 3);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Sandoz Inc.', 4);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Jafra Cosmetics', 5);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'McKesson Contract Packaging', 6);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Aurobindo Pharma Limited', 7);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Unit Dose Services', 8);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Medicine Shoppe International Inc', 9);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Graceway Pharmaceuticals, LLC', 10);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'American Sales Company', 11);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Natural Health Supply', 12);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Proficient Rx LP', 13);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'NorthStar RX LLC', 14);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Western Family Foods, Inc.', 15);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'My Habitat Brands LLC', 16);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Torrent Pharmaceuticals Limited', 17);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'American Health Packaging', 18);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'CVS Pharmacy Inc', 19);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Neutrogena Corporation', 20);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Bayer HealthCare Pharmaceuticals Inc.', 21);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Watson Laboratories, Inc.', 22);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Sandoz Canada Inc', 23);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Paramesh Banerji Life Sciences LLC', 24);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Greenstone LLC', 25);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Ricola Ag', 26);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'ALK-Abello, Inc.', 27);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'REMEDYREPACK INC.', 28);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Reckitt Benckiser LLC', 29);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Lil'' Drug Store Products, Inc', 30);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Medicine Shoppe International Inc', 31);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'REMEDYREPACK INC.', 32);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Cardinal Health', 33);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Coria Laboratories', 34);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Lake Erie Medical DBA Quality Care Products LLC', 35);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Med-Health Pharma, LLC', 36);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Rouses Point Pharm', 37);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Newton Laboratories, Inc.', 38);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'CHAIN DRUG CONSORTIUM, LLC', 39);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Avon Products, Inc.', 40);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Rebel Distributors Corp', 41);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Zeus Medical Holdings LLC', 42);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Newton Laboratories, Inc.', 43);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'BrandStorm HBC', 44);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Clinical Solutions Wholesale', 45);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'OnPoint, Inc', 46);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Valu Merchandisers Company', 47);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Carilion Materials Management', 48);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Preferred Pharmaceuticals, Inc.', 49);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'LABORATOIRE NUXE', 50);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Laboratoires Clarins S.A.', 51);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Ranbaxy Pharmaceuticals Inc.', 52);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Washington Homeopathic Products', 53);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Actavis Elizabeth LLC', 54);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Golden State Medical Supply', 55);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'ZEE MEDICAL', 56);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Mylan Institutional Inc.', 57);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Physicians Total Care, Inc.', 58);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Sato Pharmaceutical, Co., Ltd.', 59);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Pfizer Consumer Healthcare', 60);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'CVS Pharmacy', 61);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'DAVA Pharmaceuticals Inc', 62);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Autumn Harp, Inc.', 63);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Supervalu Inc', 64);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Antigen Laboratories, Inc.', 65);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Conopco Inc. d/b/a Unilever', 66);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Nelco Laboratories, Inc.', 67);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Rebel Distributors Corp', 68);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'American Health Packaging', 69);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Eight and Company', 70);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Sanum Kehlbeck GmbH & Co. KG', 71);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'REMEDYREPACK INC.', 72);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Jubilant HollisterStier LLC', 73);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'AvPAK', 74);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'McKesson', 75);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'General Injectables & Vaccine, Inc', 76);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Avon Products, Inc.', 77);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Arbonne International, LLC', 78);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'STAT RX LLC USA', 79);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Upsher-Smith Laboratories, Inc.', 80);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Mylan Pharmaceuticals Inc.', 81);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Arbor Pharmaceuticals, Inc.', 82);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Upsher-Smith Laboratories, Inc.', 83);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Lannett Company, Inc.', 84);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Northwind Pharmaceuticals', 85);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Amneal Pharmaceuticals of New York, LLC', 86);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'State of Florida DOH Central Pharmacy', 87);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Qualitest Pharmaceuticals', 88);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Jubilant HollisterStier LLC', 89);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'PD-Rx Pharmaceuticals, Inc.', 90);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Select Brand', 91);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Procter & Gamble Manufacturing Co.', 92);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Rugby Laboratories Inc.', 93);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Supervalu Inc', 94);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Mylan Pharmaceuticals Inc.', 95);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', 96);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Novel Laboratories, Inc.', 97);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Procter & Gamble Manufacturing Company', 98);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Virtus Pharmaceuticals LLC', 99);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Belmora LLC', 100);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'GE Healthcare Inc.', 101);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'AMI Cosmetic Co.,Ltd.', 102);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'C.B. Fleet Company, Inc.', 103);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Supervalu Inc', 104);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Jubilant HollisterStier LLC', 105);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Amerisource Bergen', 106);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'General Injectables and Vaccines, Inc', 107);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'E.R. Squibb & Sons, L.L.C.', 108);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Physicians Total Care, Inc.', 109);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Zydus Pharmaceuticals (USA) Inc.', 110);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Physicians Total Care, Inc.', 111);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Jafra Cosmetics International Inc', 112);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Rij Pharmaceutical Corporation', 113);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Genzyme Corporation', 114);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Nelco Laboratories, Inc.', 115);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Fenwal, Inc.', 116);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'THE KROGER CO', 117);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'REMEDYREPACK INC.', 118);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Amerisource Bergen', 119);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Western Family Foods, Inc.', 120);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'McKesson Contract Packaging', 121);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'CRC Industries, Inc.', 122);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'New GPC, Inc.', 123);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Deb USA, Inc.', 124);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Cardinal Health', 125);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Wakefern Food Corporation', 126);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Nelco Laboratories, Inc.', 127);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Meijer Distribution Inc', 128);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Physicians Total Care, Inc.', 129);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Nelco Laboratories, Inc.', 130);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'KAISER FOUNDATION HOSPITALS', 131);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'BluePoint Laboratories', 132);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Advanced Hygienics LLC', 133);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Sagent Pharmaceuticals', 134);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Sun Pharmaceutical Industries Limited', 135);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Kingsway', 136);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Rebel Distributors Corp', 137);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Nature''s Innovation, Inc.', 138);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Natural Health Supply', 139);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'E. FOUGERA & CO. A division of Fougera Pharmaceuticals Inc.', 140);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Taro Pharmaceuticals U.S.A., Inc.', 141);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'McKesson Medical-Surgical Inc.', 142);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Baxter Healthcare Corporation', 143);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Amneal Pharmaceuticals', 144);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'SHISEIDO AMERICA INC.', 145);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Uriel Pharmacy Inc.', 146);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Dr. Reddy''s Laboratories Limited', 147);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Genentech, Inc.', 148);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Conopco Inc. d/b/a Unilever', 149);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Liddell Laboratories, Inc.', 150);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Energizer Personal Care LLC', 151);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'ALK-Abello, Inc.', 152);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Bryant Ranch Prepack', 153);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Procter & Gamble Manufacturing Co.', 154);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Legacy Pharmaceutical Packaging', 155);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Prime Enterprises, Inc.', 156);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Premier Brands of America Inc.', 157);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Takeda Pharmaceuticals America, Inc.', 158);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Kroger Company', 159);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Watson Laboratories, Inc.', 160);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'TYA Pharmaceuticals', 161);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Bryant Ranch Prepack', 162);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'REMEDYREPACK INC.', 163);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'PD-Rx Pharmaceuticals, Inc.', 164);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Good Neighbor Pharmacy', 165);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'General Injectables & Vaccines, Inc', 166);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'SJ Creations, Inc.', 167);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'General Injectables & Vaccine, Inc', 168);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Washington Homeopathic Products', 169);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Nelco Laboratories, Inc.', 170);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'McKesson', 171);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Lake Erie Medical DBA Quality Care Products LLC', 172);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'AMOREPACIFIC', 173);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Antigen Laboratories, Inc.', 174);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Antigen Laboratories, Inc.', 175);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Avadim Technologies, Inc.', 176);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Alva-Amco Pharmacal Companies, Inc.', 177);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'MallyGirl, LLC', 178);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'NCS HealthCare of KY, Inc dba Vangard Labs', 179);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Aurobindo Pharma Limited', 180);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Legacy Pharmaceutical Packaging', 181);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Shopko Stores Operating Co., LLC', 182);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Rite Aid', 183);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Greenstone LLC', 184);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'McKesson Contract Packaging', 185);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Nelco Laboratories, Inc.', 186);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'ALK-Abello, Inc.', 187);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'SHISEIDO AMERICA INC.', 188);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Cardinal Health', 189);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'ALK-Abello, Inc.', 190);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Amneal Pharmaceuticals, LLC', 191);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'CVS Pharmacy', 192);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Libertas Pharma Inc.', 193);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Cardinal Helath', 194);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', 195);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Antigen Laboratories, Inc.', 196);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Greenstone LLC', 197);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'DIRECT RX', 198);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Aqua Pharmaceuticals', 199);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Unique First Aid Corporation', 200);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Johnson & Johnson Consumer Products Company Inc.', 201);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Bryant Ranch Prepack', 202);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Antigen Laboratories, Inc.', 203);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'SHISEIDO CO., LTD.', 204);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Teva Pharmaceuticals USA Inc', 205);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Barr Laboratories Inc.', 206);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Erno Laszlo, Inc.', 207);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'The Mentholatum Company', 208);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'McKesson', 209);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Cardinal Health', 210);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Cardinal Health', 211);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'ALK-Abello, Inc.', 212);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'LIVE BETTER (The Great Atlantic & Pacific Tea Company)', 213);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Burke Therapeutics, LLC', 214);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Jinju Bio Food', 215);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Merck Sharp & Dohme Corp.', 216);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Geri-Care Pharmaceuticals, Corp', 217);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Mallinckrodt Inc.', 218);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Sam''s West Inc', 219);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Atlantic Biologicals Corps', 220);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Zogenix, Inc.', 221);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Lannett Company, Inc.', 222);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'AAA Pharmaceutical, Inc.', 223);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Major Pharmaceuticals', 224);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'DOLGENCORP, LLC', 225);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Citron Pharma LLC', 226);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'CVS Pharmacy', 227);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Sancilio & Company Inc.', 228);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'MAJOR Pharmaceuticals Inc.', 229);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'The Mentholatum Company', 230);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Remedy Makers', 231);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'REMEDYREPACK INC.', 232);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'SJ Creations, Inc.', 233);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Nelco Laboratories, Inc.', 234);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Preferred Pharmaceuticals, Inc.', 235);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Publix Super Markets Inc', 236);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Dr.Reddy''s Laboratories Limited', 237);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'WALGREEN CO.', 238);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Physicians Total Care, Inc.', 239);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'White Manufacturing Incorporated DBA Micro-West', 240);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Laboratorios Quantium LLC', 241);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Darby Dental Supply Co Inc', 242);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'BGR Enterprises, Inc. dba Penn Oxygen & Supply Company', 243);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Physicians Total Care, Inc.', 244);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'AvKARE, Inc.', 245);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Major Pharmaceuticals', 246);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Torrent Pharmaceuticals Limited', 247);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Moore Medical', 248);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'EQUATE (Walmart Stores, Inc.)', 249);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'QUALITY CHOICE (Chain Drug Marketing Association)', 250);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Church & Dwight Co., Inc.', 251);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Mary Kay Inc.', 252);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Apotex Corp.', 253);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Natura Bisse International', 254);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Aurobindo Pharma Limited', 255);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Mary Kay Inc.', 256);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Walmart Stores Inc.', 257);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Apotex Corp.', 258);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Physicians Total Care, Inc.', 259);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'JAFRA COSMETICS INTERNATIONAL', 260);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'BGR Enterprises, Inc. dba Penn Oxygen & Supply Company', 261);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'NATURE REPUBLIC CO., LTD.', 262);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Ultradent Products, Inc.', 263);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Cardinal Health', 264);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Pfizer Consumer Healthcare', 265);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'AN Co Ltd.', 266);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Preferred Pharmaceuticals, Inc', 267);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'C.O. Truxton, Inc.', 268);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Nelco Laboratories, Inc.', 269);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Antigen Laboratories, Inc.', 270);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'American Airlines, Inc.', 271);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Personal Care Products, Inc.', 272);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Newton Laboratories, Inc.', 273);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Korea Ginseng Corporation', 274);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Meijer Distribution Inc', 275);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', 276);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Aphena Pharma Solutions - Tennessee, LLC', 277);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'NATURE REPUBLIC CO., LTD.', 278);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Bolero Home Decor, Inc.', 279);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'SKinfOD CO., LTD.', 280);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Cardinal Health', 281);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'International Beauty Exchange', 282);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'REMEDYREPACK INC.', 283);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Supervalu Inc', 284);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Aurobindo Pharma Limited', 285);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Aidance Skincare & Topical Solutions, LLC', 286);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'State of Florida DOH Central Pharmacy', 287);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'CHANEL PARFUMS BEAUTE', 288);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Dispensing Solutions, Inc.', 289);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Upsher-Smith Laboratories, Inc.', 290);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Teva Pharmaceuticals USA Inc', 291);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Cardinal Health', 292);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'UNITED EXCHANGE CORP', 293);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Publix Super Markets Inc', 294);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Physicians Total Care, Inc.', 295);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Physicians Total Care, Inc.', 296);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Walgreen Company', 297);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Allure Labs, Inc.', 298);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Wockhardt USA LLC.', 299);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Phillips Company', 300);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'L.N.K. International, Inc.', 301);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Mikart, Inc.', 302);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'CVS Pharmacy', 303);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Clinical Solutions Wholesale', 304);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'McKesson Packaging Services a business unit of McKesson Corporation', 305);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'ALK-Abello, Inc.', 306);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Aloe Vera of America, Inc.', 307);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Cardinal Health', 308);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Pan Aromas LLC', 309);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Sandoz Inc', 310);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Major Pharmaceuticals', 311);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'ARMY AND AIR FORCE EXCHANGE SERVICE', 312);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Liddell Laboratories, Inc.', 313);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Aplicare, Inc.', 314);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Physicians Total Care, Inc.', 315);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Cantrell Drug Company', 316);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'The Mentholatum Company', 317);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Lornamad', 318);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Ovelle Ltd', 319);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Teva Pharmaceuticals USA Inc', 320);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'MAKEUP ART COSMETICS', 321);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Select Brand', 322);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'AvPAK', 323);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Hospira, Inc.', 324);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Church & Dwight Co., Inc.', 325);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Barr Laboratories Inc.', 326);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Apotheca Company', 327);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Speer Laboratories, LLC', 328);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Wyeth BioPharma Division of Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', 329);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'E-Z-EM Canada Inc', 330);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Baoying County Fukang Medical Appliance Co., Ltd.', 331);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'MULTALER & CIE S.A.', 332);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'GlaxoSmithKline LLC', 333);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Aidarex Pharmaceuticals LLC', 334);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Delilah Cosmetics', 335);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Cardinal Health', 336);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Mallinckrodt Inc.', 337);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Aidarex Pharmaceuticals LLC', 338);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'American Regent, Inc.', 339);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Mutual Pharmaceutical Company, Inc.', 340);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Similasan Corporation', 341);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Rebel Distributors Corp', 342);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Insight Pharmaceuticals', 343);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'WALGREEN CO.', 344);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Ecolab Inc.', 345);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'CoValence, Inc.', 346);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Supervalu Inc', 347);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Dispensing Solutions, Inc.', 348);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Claris Lifesciences Inc.', 349);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Hevert Pharmaceuticals, Inc.', 350);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Watson Laboratories, Inc.', 351);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Discount Drug Mart', 352);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'AFFLABS, Affiliated Laboratories, A Division of AFFLINK', 353);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Northstar RxLLC', 354);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Benefit Cosmetics, LLC', 355);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Golden State Medical Supply, Inc', 356);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Roberts Oxygen Company, Inc.', 357);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Nelco Laboratories, Inc.', 358);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'FOCUS Laboratories, Inc.', 359);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'MedVantx, Inc.', 360);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'PuraVation Pharmaceuticals Inc', 361);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'State of Florida DOH Central Pharmacy', 362);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'University Medical Pharmaceuticals Corp', 363);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'CVS Pharmacy, Inc.', 364);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Greenstone LLC', 365);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Sam''s West Inc', 366);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Camber Pharmaceuticals, Inc.', 367);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'ALVOGEN INC.', 368);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Sandoz Inc', 369);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Hyland''s', 370);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Kimberly-Clark Corporation', 371);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Nelco Laboratories, Inc.', 372);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Supervalu Inc', 373);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'CLINIQUE LABORATORIES INC.', 374);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Cardinal Health', 375);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Physicians Total Care, Inc.', 376);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Nelco Laboratories, Inc.', 377);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'AMOREPACIFIC', 378);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'ATOMY CO., LTD.', 379);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Cardinal Health', 380);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Cardinal Health', 381);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Walgreens', 382);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'APP Pharmaceuticals, LLC', 383);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Amerisource Bergen', 384);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'H and P Industries, Inc. dba Triad Group', 385);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Noven Therapeutics, LLC', 386);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'ADBIOTECH CO., LTD.', 387);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Watson Laboratories, Inc.', 388);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Uriel Pharmacy Inc.', 389);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', 390);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Uriel Pharmacy Inc.', 391);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Mylan Pharmaceuticals Inc.', 392);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Rebel Distributors Corp', 393);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Actavis Pharma, Inc.', 394);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'HART Health', 395);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Apotheca, Company', 396);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Estee Lauder Inc.', 397);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Wal-Mart Stores Inc', 398);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'A-S Medication Solutions LLC', 399);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'CareStream Health, Inc.', 400);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'REMEDYREPACK INC.', 401);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Laboratoires Clarins S.A.', 402);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Shasun Pharmaceuticals Limited', 403);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Uriel Pharmacy Inc.', 404);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Aidarex Pharmaceuticals LLC', 405);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'GOJO Industries, Inc.', 406);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Cadila Healthcare Limited', 407);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Parfums Christian Dior', 408);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'RUGBY LABORATORIES, INC.', 409);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Dr.Reddy''s Laboratories Limited', 410);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Xiamen Olivee Daily Use Chemical Co., Ltd.', 411);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Lupin Pharmaceuticals, Inc.', 412);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Allergy Laboratories, Inc.', 413);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Napoleon Perdis Cosmetics, Inc', 414);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Golden State Medical Supply, Inc.', 415);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Walgreen Company', 416);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Qualitest Pharmaceuticals', 417);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Preferred Pharmaceuticals, Inc.', 418);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Dentsply Pharmaceutical', 419);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Northwind Pharmaceuticals', 420);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Physicians Total Care, Inc.', 421);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'BioActive Nutritional, Inc.', 422);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Home Sweet Homeopathics', 423);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Physicians Total Care, Inc.', 424);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Physicians Total Care, Inc.', 425);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'B8 Sales, Inc.', 426);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Novartis Pharmaceuticals Corporation', 427);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Citron Pharma LLC', 428);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Taro Pharmaceuticals U.S.A., Inc.', 429);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Kramer Laboratories', 430);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Nelco Laboratories, Inc.', 431);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Eli Lilly and Company', 432);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Cantrell Drug Company', 433);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Theravance Biopharma Antibiotics, Inc.', 434);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'AstraZeneca Pharmaceuticals LP', 435);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'American Sales Company', 436);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'bryant ranch prepack', 437);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Lupin Pharmaceuticals, Inc.', 438);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Rite Aid Corporation', 439);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Baxter Healthcare Corporation', 440);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Greenstone LLC', 441);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Cyclotron Partners LP dba Cyclotope', 442);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Topco Associates LLC', 443);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Meijer Distribution, Inc', 444);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Walgreen Company', 445);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Antigen Laboratories, Inc.', 446);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'VVF Kansas Services LLC', 447);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'SHISEIDO CO., LTD.', 448);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'McKesson', 449);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'McKesson Packaging Services a business unit of McKesson Corporation', 450);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Uriel Pharmacy Inc.', 451);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'AMOREPACIFIC', 452);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Bryant Ranch Prepack', 453);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'ALK-Abello, Inc.', 454);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Washington Homeopathic Products', 455);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'US MedSource, LLC', 456);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Cardinal Health', 457);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'AvKARE, Inc.', 458);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Nelco Laboratories, Inc.', 459);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Phoenix Global Supply Group, Inc', 460);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Hameln Pharma GmbH', 461);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Melaleuca, Inc.', 462);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Fresenius Kabi USA, LLC', 463);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'ALK-Abello, Inc.', 464);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Sanofi-Aventis U.S. LLC', 465);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Cardinal Health', 466);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Gilead Sciences, Inc.', 467);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Major Pharmaceuticals', 468);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Mylan Institutional Inc.', 469);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Sandoz Inc', 470);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Aphena Pharma Solutions - Tennessee, LLC', 471);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Novartis Consumer Health, Inc.', 472);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'ALK-Abello, Inc.', 473);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Menper Distributors, Inc.', 474);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Lake Erie Medical DBA Quality Care Products LLC', 475);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Mission Hills S.A de C.V', 476);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'L. Perrigo Company', 477);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'CSL Behring AG', 478);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'St Marys Medical Park Pharmacy', 479);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Nelco Laboratories, Inc.', 480);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Bionutrigen Co., Ltd.', 481);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Allermed Laboratories, Inc.', 482);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Worldwide Sales & Distribution Corp.', 483);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Par Pharmaceutical Companies, Inc.', 484);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Physicians Total Care, Inc.', 485);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Laurus Enterprises, LLC', 486);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'HOMEOLAB USA INC.', 487);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Cardinal Health', 488);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'REMEDYREPACK INC.', 489);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Parfums Christian Dior', 490);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Par Pharmaceuticals, Inc.', 491);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Chain Drug Marketing Association', 492);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Apotex Corp', 493);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Jubilant HollisterStier LLC', 494);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Ole Henriksen of Denmark', 495);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'WAL-MART STORES INC.', 496);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'BioActive Nutritional, Inc.', 497);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Gen-Source Rx', 498);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Natural Health Supply', 499);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Topco Associates LLC', 500);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'AGILA SPECIALTIES PRIVATE LIMITED', 501);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'F&CO Co., Ltd.', 502);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Contract Pharmacy Services-PA', 503);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'PD-Rx Pharmaceuticals, Inc.', 504);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Pan Aromas LLC', 505);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'EBAIN Corporation Co., Ltd.', 506);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Dr.Reddy''s Laboratories Limited', 507);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'PUREMEDY', 508);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Roerig', 509);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'LABORATORIOS SOPHIA, S.A. DE C.V.', 510);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Apotex Corp.', 511);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Blenheim Pharmacal, Inc.', 512);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Preferred Plus (Kinray)', 513);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Uriel Pharmacy Inc.', 514);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Nelco Laboratories, Inc.', 515);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Medicis Pharmaceutical Corp', 516);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Lannett Company, Inc.', 517);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'American Health Packaging', 518);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Accord Healthcare Inc.', 519);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Topco Associates LLC', 520);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'AMOREPACIFIC', 521);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Kroger Co.', 522);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'REMEDYREPACK INC.', 523);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'ILMO Products Company', 524);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Amgen Inc', 525);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Jubilant HollisterStier LLC', 526);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'LG Household and Healthcare, Inc.', 527);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Meijer Distribution Inc', 528);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Wal-Mart Stores Inc', 529);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'MSD Consumer Care, Inc.', 530);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'ALK-Abello, Inc.', 531);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'TRIZ LABORATORIES LTD', 532);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'ALK-Abello, Inc.', 533);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'CVS Pharmacy', 534);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'McNeil Consumer Healthcare Div. McNeil-PPC, Inc', 535);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Cardinal Health', 536);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'NCS HealthCare of KY, Inc dba Vangard Labs', 537);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Genesis Pharmaceutical, Inc.', 538);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Nelco Laboratories, Inc.', 539);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'BioActive Nutritional, Inc.', 540);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'AIRGAS-NORPAC INC.', 541);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'King Bio Inc', 542);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Unifirst First Aid Corporation', 543);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'American Health Packaging', 544);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Native Remedies, LLC', 545);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Results RNA, LLC', 546);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Physicians Total Care, Inc.', 547);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Bare Escentuals Beauty Inc.', 548);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Unit Dose Services', 549);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Sandoz Inc', 550);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Lehigh Valley Respiratory Care, Lancaster', 551);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Brioschi Pharmaceuticals International, LLC', 552);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'The Mentholatum Company', 553);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Validus Pharmaceuticals LLC', 554);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Target Corporation', 555);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Nutri-Dyn Products Ltd. dba Professional Health Products', 556);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Healing Natural Oils', 557);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Valeant Pharmaceuticals North America LLC', 558);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'STAT Rx USA LLC', 559);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Boscia LLC', 560);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Nelco Laboratories, Inc.', 561);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Uriel Pharmacy Inc.', 562);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Aurobindo Pharma Limited', 563);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Antigen Laboratories, Inc.', 564);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Rebel Distributors Corp', 565);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'KAISER FOUNDATION HOSPITALS', 566);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Changzhou Maokang Medical Products Co., Ltd', 567);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Antigen Laboratories, Inc.', 568);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Actavis Elizabeth LLC', 569);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Akorn, Inc.', 570);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Apotheca Company', 571);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'King Bio Inc.', 572);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'GlaxoSmithKline LLC', 573);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'NCS HealthCare of KY, Inc dba Vangard Labs', 574);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Jubilant HollisterStier LLC', 575);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Medline Industries, Inc.', 576);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Eon Labs, Inc.', 577);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Apotex Corp.', 578);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Legacy Pharmaceutical Packaging', 579);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'PD-Rx Pharmaceuticals, Inc.', 580);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Antigen Laboratories, Inc.', 581);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Burel Pharmaceuticals, LLC', 582);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Rebel Distributors Corp', 583);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'MC Group Development Ltd.', 584);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Shopko Stores Operating Co., LLC', 585);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'NSE Products, Inc.', 586);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Physicians Total Care, Inc.', 587);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', 588);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Phoenix Pharmaceutical, Inc.', 589);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'NATURE REPUBLIC CO., LTD.', 590);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Qualitest Pharmaceuticals', 591);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Dolgencorp, LLC', 592);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Antigen Laboratories, Inc.', 593);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'St Marys Medical Park Pharmacy', 594);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Pharmaceutical Associates, Inc.', 595);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'True Botanica, LLC', 596);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Lake Erie Medical DBA Quality Care Products LLC', 597);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Apotheca, Inc.', 598);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Blacksmith Brands, Inc.', 599);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'KANEBO COSMETICS INC', 600);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Parke-Davis Div of Pfizer Inc', 601);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Dr. Reddy''s Laboratories Limited', 602);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Neutrogena Corporation', 603);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'APP Pharmaceuticals, LLC', 604);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'ABC Compounding Co., Inc.', 605);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Deseret Biologicals, Inc.', 606);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Carilion Materials Management', 607);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Atlantic Biologicals Corps', 608);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Amneal Pharmaceuticals', 609);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Target Corp', 610);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Aphena Pharma Solutions - Tennessee, LLC', 611);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'REMEDYREPACK INC.', 612);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Kaiser Foundation Hospitals', 613);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Teva Parenteral Medicines, Inc.', 614);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'ARMY AND AIR FORCE EXCHANGE SERVICE', 615);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Barr Laboratories Inc.', 616);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Hospira, Inc.', 617);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'philosophy', 618);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'G&W Laboratories, Inc.', 619);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'ReadyMeds', 620);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Bolero Home Decor, Inc.', 621);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Proficient Rx LP', 622);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'WOONSOCKET PRESCRIPTION CENTER,INCORPORATED', 623);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Med-Health Pharma, LLC', 624);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Duane Reade', 625);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Major Pharmaceuticals', 626);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'FSC Laboratories, Inc', 627);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'TYA Pharmaceuticals', 628);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'STAT Rx USA LLC', 629);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Merck Sharp & Dohme Corp.', 630);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Apotex Corp', 631);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'E.R. Squibb & Sons, L.L.C.', 632);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Cardinal Health', 633);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Aphena Pharma Solutions - Tennessee, LLC', 634);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Jiangsu Province JianErKang Medical Dressing Co. ,Ltd.', 635);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Physicians Total Care, Inc.', 636);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Torrent Pharmaceuticals Limited', 637);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'RDM Products, Inc', 638);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Nova Homeopathic Therapeutics, Inc.', 639);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Cardinal Health', 640);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Unit Dose Services', 641);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'American Sales Company', 642);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Eon Labs, Inc.', 643);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Physician Therapeutics LLC', 644);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Antigen Laboratories, Inc.', 645);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Apotheca Company', 646);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Baxter Healthcare Corporation', 647);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'American Regent, Inc.', 648);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Meijer Distribution Inc', 649);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'REMEDYREPACK INC.', 650);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Taro Pharmaceuticals U.S.A., Inc.', 651);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Henry Schein, Inc.', 652);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Greenstone LLC', 653);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Teva Pharmaceuticals USA Inc', 654);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Fedora International Co., Ltd.', 655);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Golden State Medical Supply, Inc.', 656);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Warner Chilcott (US), LLC', 657);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'CCA Industries Inc', 658);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Yves Rocher North America Inc. DBA Laboratoire de biologie vegetal Yves Rocher', 659);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Preferred Pharmaceuticals, Inc.', 660);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Hospira, Inc.', 661);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'ALK-Abello, Inc.', 662);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'H.J. Harkins Company, Inc.', 663);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Bare Escentuals Beauty Inc.', 664);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'North Central Respiratory, Inc', 665);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Shire US Manufacturing Inc.', 666);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'ARMY AND AIR FORCE EXCHANGE SERVICE', 667);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'General Injectables & Vaccines, Inc', 668);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Rugby Laboratories Inc.', 669);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'L. Perrigo Company', 670);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Neutrogena Corporation', 671);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Shire US Manufacturing Inc.', 672);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Ascend Laboratories, LLC', 673);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Fresenius Kabi USA, LLC', 674);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Johnson & Johnson Healthcare Products, Division of McNEIL-PPC, Inc.', 675);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Procter & Gamble Manufacturing Company', 676);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'NCS HealthCare of KY, Inc dba Vangard Labs', 677);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Sun Pharma Global FZE', 678);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Nelco Laboratories, Inc.', 679);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Cadila Healthcare Limited', 680);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Unifirst First Aid Corporation', 681);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'REMEDYREPACK INC.', 682);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Medline Industries, Inc.', 683);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Lake Welding Supply Company', 684);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Nelco Laboratories, Inc.', 685);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Ventura Corporation LTD', 686);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'The Hain Celestial Group, Inc.', 687);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Teva Pharmaceuticals USA Inc', 688);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'B. Braun Medical Inc.', 689);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'North Central Respiratory, Inc', 690);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Qualitest Pharmaceuticals', 691);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Mylan Institutional Inc.', 692);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Menper Distributors, Inc.', 693);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Cardinal Health', 694);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Bolero Home Decor, Inc.', 695);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Chain Drug Marketing Association Inc', 696);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Rebel Distributors Corp', 697);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Novartis Consumer Health', 698);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Cardinal Health', 699);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'PHARMAZEUTISCHE FABRIK DR. RECKEWEG & CO', 700);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Blenheim Pharmacal, Inc.', 701);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Melaleuca, Inc.', 702);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Conopco Inc. d/b/a Unilever', 703);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Home Sweet Homeopathics', 704);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Actavis Mid Atlantic LLC', 705);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'American Health Packaging', 706);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'MWI/VetOne', 707);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'McKesson', 708);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Meijer Distribution Inc', 709);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Qualitest Pharmaceuticals', 710);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Energizer Personal Care LLC', 711);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Physicians Total Care, Inc.', 712);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Hisamitsu America, Inc.', 713);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'STAT RX USA LLC', 714);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'REMEDYREPACK INC.', 715);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Physicians Total Care, Inc.', 716);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Goodier Cosmetics LP', 717);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'ALK-Abello, Inc.', 718);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'MAJOR PHARMACEUTICALS INC', 719);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Guerlain S.A', 720);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Santarus, Inc.', 721);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Aphena Pharma Solutions - Tennessee, Inc.', 722);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Mylan Pharmaceuticals Inc.', 723);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Physicians Total Care, Inc.', 724);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Advanced Beauty Systems, Inc.', 725);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Clinical Solutions Wholesale', 726);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Mylan Institutional Inc.', 727);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'International Nature Nutraceuticals', 728);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Ventura Corporation LTD', 729);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Aphena Pharma Solutions - Tennessee, LLC', 730);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Cardinal Health', 731);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Medsep Corporation', 732);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Rebel Distributors Corp', 733);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Contract Pharmacy Services-PA', 734);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'ALK-Abello, Inc.', 735);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Taro Pharmaceuticals U.S.A., Inc.', 736);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Wyeth Pharmaceuticals Inc., a subsidiary of Pfizer Inc.', 737);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Bryant Ranch Prepack', 738);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'DZA Brands LLC', 739);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Chattem, Inc.', 740);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Uriel Pharmacy Inc.', 741);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Mylan Pharmaceuticals Inc.', 742);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Dharma Research, inc.', 743);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'ALK-Abello, Inc.', 744);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Wal-Mart Stores Inc', 745);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'American Health Packaging', 746);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'SHISEIDO AMERICA INC.', 747);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'HyVee Inc', 748);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'KAISER FOUNDATION HOSPITALS', 749);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'REMEDYREPACK INC.', 750);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'NARTEX LABORATORIOS HOMEOPATICOS SA DE CV', 751);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Mon HealthCare', 752);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Golden State Medical Supply, Inc.', 753);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Elizabeth Arden, Inc', 754);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Novartis Pharmaceuticals Corporation', 755);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Jiangsu Province JianErKang Medical Dressing Co. ,Ltd.', 756);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'King Bio, Inc.', 757);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Walgreen Company', 758);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Supervalu Inc', 759);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'MAKE-UP ART COSMETICS', 760);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Preferred Pharmaceuticals, Inc.', 761);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Sanum Kehlbeck GmbH & Co. KG', 762);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'H E B', 763);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Uriel Pharmacy Inc.', 764);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Henry Schein, Inc.', 765);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'BioActive Nutritional, Inc.', 766);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Bolero Home Decor, Inc.', 767);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Major Pharmaceuticals', 768);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Walgreen Company', 769);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Galderma Laboratories, L.P.', 770);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Hyland''s', 771);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'MedVantx, Inc.', 772);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'GREAT LAKES WHOLESALE, MARKETING, & SALES, INC.', 773);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Greenstone LLC', 774);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'ALK-Abello, Inc.', 775);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Nelco Laboratories, Inc.', 776);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Aidarex Pharmaceuticals LLC', 777);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Preferred Pharmaceuticals, Inc.', 778);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'REMEDYREPACK INC.', 779);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'REMEDYREPACK INC.', 780);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Mckesson', 781);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Apotheca Company', 782);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'CVS Pharmacy', 783);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'PureTek Corporation', 784);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'International Cosmetics Ltd.', 785);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'State of Florida DOH Central Pharmacy', 786);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Tarte, Inc', 787);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'HAMSOA PHARMACEUTICAL CO., LTD.', 788);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'AMOREPACIFIC', 789);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Nelco Laboratories, Inc.', 790);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Lannett Company, Inc.', 791);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'General Injectables & Vaccines, Inc.', 792);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'CorePharma, LLC', 793);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Henry Schein, Inc.', 794);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Cadila Healthcare Limited', 795);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Hospira, Inc.', 796);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'SHISEIDO AMERICA INC.', 797);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'State of Florida DOH Central Pharmacy', 798);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Lupin Pharmaceuticals, Inc.', 799);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Sagent Pharmaceuticals', 800);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Nelco Laboratories, Inc.', 801);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Nelco Laboratories, Inc.', 802);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Carlsbad Technology, Inc.', 803);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'GlaxoSmithKline LLC', 804);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Preferred Pharmaceuticals, Inc.', 805);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Medline Industries, Inc.', 806);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Dispensing Solutions, Inc.', 807);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Kremers Urban Pharmaceuticals Inc', 808);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Uriel Pharmacy Inc.', 809);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Wallace Pharmaceuticals Inc.', 810);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Glenmark Generics Inc., USA', 811);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Cadila Healthcare Limited', 812);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Dukal Corporation', 813);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Pack Pharmaceuticals, LLC', 814);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Amneal Pharmaceuticals', 815);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'ALK-Abello, Inc.', 816);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'St Marys Medical Park Pharmacy', 817);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'WALGREEN CO.', 818);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'ALK-Abello, Inc.', 819);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'AvKARE, Inc.', 820);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Nelco Laboratories, Inc.', 821);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Par Pharmaceutical Companies, Inc.', 822);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'McKesson Contract Packaging', 823);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Teva Pharmaceuticals USA Inc', 824);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Valu Merchandisers Company', 825);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'NATURE REPUBLIC CO., LTD.', 826);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'BioActive Nutritional, Inc.', 827);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'McKesson Medical-Surgical', 828);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Deseret Biologicals, Inc.', 829);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'American Sales Company', 830);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Chattem, Inc.', 831);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'PuraVation Pharmaceuticals Inc', 832);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Mylan Institutional Inc.', 833);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'EQUATE (Walmart Stores, Inc.)', 834);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Conopco Inc. d/b/a Unilever', 835);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Rite Aid', 836);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'AnazaoHealth Corporation', 837);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Procter & Gamble Manufacturing Company', 838);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'A-S Medication Solutions LLC', 839);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Mylan Pharmaceuticals Inc.', 840);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Aphena Pharma Solutions - Tennessee, LLC', 841);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Dispensing Solutions, Inc.', 842);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'ALK-Abello, Inc.', 843);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'CVS Pharmacy', 844);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'A-S Medication Solutions LLC', 845);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Johnson & Johnson Healthcare Products, Division of McNEIL-PPC, Inc.', 846);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Zee Medical Inc', 847);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Teva Pharmaceuticals USA Inc', 848);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Teva Pharmaceuticals USA Inc', 849);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'ENCHANTE ACCESSORIES INC.', 850);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Allergy Laboratories, Inc.', 851);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Hospira, Inc.', 852);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Hy-Vee', 853);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Hydrox Laboratories', 854);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'SHISEIDO AMERICAS CORPORATION', 855);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Purdue Pharma LP', 856);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'NCS HealthCare of KY, Inc dba Vangard Labs', 857);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'CVS Pharmacy', 858);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Teva Pharmaceuticals USA Inc', 859);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Premiere Enterprises', 860);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Unifirst First Aid Corporation', 861);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Topco Associates LLC', 862);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'PD-Rx Pharmaceuticals, Inc.', 863);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'ALK-Abello, Inc.', 864);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Accord Healthcare Inc', 865);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Apotheca Company', 866);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Air Source Industries Inc', 867);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Lanocorp Pacific Ltd', 868);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Nelco Laboratories, Inc.', 869);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'REMEDYREPACK INC.', 870);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Actavis Elizabeth LLC', 871);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'The Procter & Gamble Manufacturing Company', 872);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Nelco Laboratories, Inc.', 873);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Pfizer Consumer Healthcare', 874);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Reckitt Benckiser LLC', 875);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Merle Norman Cosmetics', 876);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Lake Erie Medical DBA Quality Care Products LLC', 877);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Hisamitsu Pharmaceutical Co., Inc.', 878);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'The Procter & Gamble Manufacturing Company', 879);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'American Sales Company', 880);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'ReadyMeds', 881);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Help Remedies, Inc.', 882);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Allergy Laboratories, Inc.', 883);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Eon Labs, Inc.', 884);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Preferred Pharmaceuticals, Inc.', 885);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'American Health Packaging', 886);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Pfizer Laboratories Div Pfizer Inc', 887);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'PL Developments', 888);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Med-Health Pharma, LLC', 889);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'EQUATE (Walmart Stores, Inc.)', 890);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'AMERICAN SALES COMPANY', 891);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'CareFusion 213 LLC', 892);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'NCS HealthCare of KY, Inc dba Vangard Labs', 893);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Apotheca Company', 894);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Watson Pharma, Inc.', 895);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Good Sense (Geiss, Destin & Dunn, Inc.)', 896);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Aidarex Pharmaceuticals LLC', 897);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Aurolife Pharma LLC', 898);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Mondelez Global LLC', 899);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'REMEDYREPACK INC.', 900);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Preferred Pharmaceuticals, Inc.', 901);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'KAISER FOUNDATION HOSPITALS', 902);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Boca Pharmacal, LLC', 903);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'REMEDYREPACK INC.', 904);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'NATURE REPUBLIC CO., LTD.', 905);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Actavis Elizabeth LLC', 906);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Person and Covey', 907);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Capellon Pharmaceuticals, LLC', 908);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Antigen Laboratories, Inc.', 909);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Parfums Christian Dior', 910);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Walgreen Co', 911);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Eon Labs, Inc.', 912);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Akorn, Inc.', 913);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'REMEDYREPACK INC.', 914);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Home Sweet Homeopathics', 915);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Walgreen Company', 916);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'REMEDYREPACK INC.', 917);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Liberty Pharmaceuticals, Inc.', 918);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'American Health Packaging', 919);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', 920);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Medimetriks Pharmaceuticals, Inc.', 921);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'American Sales Company', 922);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'McKesson', 923);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Woodbine Products Company', 924);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Apotheca Company', 925);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Ventura International LTD.', 926);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Mylan Pharmaceuticals Inc.', 927);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Nelco Laboratories, Inc.', 928);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Preferred Pharmaceuticals, Inc', 929);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'The Wellness Center', 930);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Cearna, Inc.', 931);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Physicians Total Care, Inc.', 932);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Genesis', 933);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Washington Homeopathic Products', 934);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Novartis Pharmaceuticals Corporation', 935);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'H E B', 936);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'West-ward Pharmaceutical Corp', 937);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'STAT RX USA LLC', 938);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Hyland''s', 939);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'West-ward Pharmaceutical Corp', 940);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Physicians Total Care, Inc.', 941);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'J.M. Murray Center Inc.', 942);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Major Pharmaceuticals', 943);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Ranbaxy Pharmaceuticals Inc.', 944);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'STAT RX USA LLC', 945);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Taro Pharmaceuticals U.S.A., Inc.', 946);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Jubilant HollisterStier LLC', 947);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'AstraZeneca Pharmaceuticals LP', 948);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'MSD Consumer Care, Inc.', 949);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'VersaPharm Incorporated', 950);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Mallinckrodt, Inc.', 951);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'State of Florida DOH Central Pharmacy', 952);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Actavis Pharma, Inc.', 953);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Shionogi Inc.', 954);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Safeway', 955);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Mylan Pharmaceuticals Inc.', 956);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Aurobindo Pharma Limited', 957);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Zydus Pharmaceuticals (USA) Inc.', 958);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Physicians Total Care, Inc.', 959);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Procter & Gamble Manufacruing Company', 960);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Neutrogena Corporation', 961);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'NCS HealthCare of KY, Inc dba Vangard Labs', 962);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'DOLGENCORP, LLC', 963);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'PACK Pharmaceuticals, LLC', 964);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('nam', 'Nelco Laboratories, Inc.', 965);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Dispensing Solutions, Inc.', 966);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Publix Super Markets, Inc', 967);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'PUREMEDY', 968);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'SPF Ventures, LLC', 969);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Barr Laboratories Inc.', 970);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'AR Scientific, Inc.', 971);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Meijer Distribution Inc', 972);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'True Botanica, LLC', 973);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Physicians Total Care, Inc.', 974);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Johnson & Johnson Consumer Products Company, Inc.', 975);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Meijer Distribution Inc', 976);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'Natural Immunogenics Corp.', 977);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Kmart Corporation', 978);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'West-ward Pharmaceutical Corp', 979);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'L''Oreal USA Products Inc', 980);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Cardinal Health Inc.', 981);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Teva Pharmaceuticals USA Inc', 982);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('com', 'REMEDYREPACK INC.', 983);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Ohm Laboratories Inc.', 984);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Legacy Pharmaceutical Packaging', 985);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Harvard Drug Group, LLC', 986);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Sohm Inc.', 987);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Kroger Company', 988);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Apotex Corp', 989);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Wockhardt Limited', 990);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Nelco Laboratories, Inc.', 991);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('gov', 'Shionogi Inc.', 992);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('edu', 'Clinical 1 Home Medical, Inc.', 993);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('org', 'Ranbaxy Pharmaceuticals Inc.', 994);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Nelco Laboratories, Inc.', 995);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Preferred Pharmaceuticals, Inc.', 996);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('mil', 'Forces of Nature', 997);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('net', 'Dr. Reddy''s Laboratories Limited', 998);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('inf', 'Uriel Pharmacy Inc.', 999);
INSERT INTO TEAM (CODE, NAME, FK_Brand_ID) values ('biz', 'Mylan Institutional Inc.', 1000);
